#!/bin/bash
# Blade & Stone build: ./build.sh [path/to/FE8U.gba] [path/to/FE7U.gba]
set -e
cd "$(dirname "$(readlink -f "$0")")"
FE8="${1:-roms/fe8u.gba}"
FE7="${2:-roms/fe7u.gba}"
export DOTNET_ROLL_FORWARD=Major
mkdir -p build
# build-time switches, e.g. BS_DEFINES="BS_DEBUG_SEIZE" ./build.sh
{ echo "// generated by build.sh"; for d in $BS_DEFINES; do echo "#define $d"; done; } > build/BuildConfig.event
cp -f "$FE8" FE8_clean.gba
python3 tools/patch_classes.py
python3 tools/patch_chars.py
python3 tools/import_fe7_faces.py "$FE7" "$FE8"
python3 tools/buildmaps.py
python3 tools/extract_tables.py "$FE8"
./MakeHack.sh "$3" 2>&1 | tee build/make.log
if grep -q "Errors occurred" build/make.log; then echo "BUILD FAILED"; grep -i "error" build/make.log; exit 1; fi
OUT="build/${BS_OUT:-BladeAndStone}.gba"
cp -f SkillsTest.gba "$OUT"
echo "Built $OUT"
