#!/bin/bash
# Blade & Stone build:  ./build.sh [FE8U.gba] [FE7U.gba]
#   -> build/BladeAndStone.gba   (+ build/BladeAndStone.ups against the clean FE8 ROM)
# Debug switches:  BS_DEFINES="BS_DEBUG_SEIZE BS_DEBUG_CH1" BS_OUT=debug ./build.sh
set -eo pipefail
cd "$(dirname "$(readlink -f "$0")")"
FE8="${1:-roms/fe8u.gba}"
FE7="${2:-roms/fe7u.gba}"
[ -f "$FE8" ] || { echo "missing clean FE8U ROM: $FE8"; exit 1; }
[ -f "$FE7" ] || { echo "missing clean FE7U ROM: $FE7"; exit 1; }
[ -d engine ] || ./setup.sh

export DEVKITPRO="${DEVKITPRO:-/opt/devkitpro}"
export DEVKITARM="${DEVKITARM:-$DEVKITPRO/devkitARM}"
export DOTNET_ROLL_FORWARD=Major
export CONFIG_EA_WIN=0

mkdir -p gen build
{ echo "// generated by build.sh"; for d in $BS_DEFINES; do echo "#define $d"; done; } > gen/BuildConfig.event.new
cmp -s gen/BuildConfig.event.new gen/BuildConfig.event || mv gen/BuildConfig.event.new gen/BuildConfig.event
rm -f gen/BuildConfig.event.new

echo "== generate"
python3 tools/import_fe7_faces.py "$FE7" "$FE8"
python3 tools/maptiles.py "$FE8"
python3 tools/buildmaps.py
python3 tools/extract_tables.py "$FE8"
python3 tools/gencast.py "$FE8" "$FE7"
python3 tools/port_banims.py "$FE8" "$FE7"
python3 tools/gentext.py
python3 tools/sync_engine.py

cmp -s "$FE8" engine/fe8.gba || cp -f "$FE8" engine/fe8.gba

echo "== engine (C-SkillSys)"
make -C engine -j"$(nproc)" 2>&1 | tee build/make.log | grep -E "^\[|rror|MESSAGE|FreeSpace|No errors" | grep -v "^\[CC \]\|^\[LYN\]" || true
if grep -qE "Errors occurred|error:|Error " build/make.log || ! grep -q "No errors" build/make.log; then
  echo "BUILD FAILED — see build/make.log"; grep -nE "rror" build/make.log | head -30; exit 1
fi
OUT="build/${BS_OUT:-BladeAndStone}.gba"
cp -f engine/fe8-kernel-dev.gba "$OUT"
python3 tools/postpatch.py "$OUT" engine/fe8-kernel-dev.sym
python3 tools/ups.py make "$FE8" "$OUT" "${OUT%.gba}.ups" >/dev/null
echo "Built $OUT ($(stat -c %s "$OUT") bytes) and ${OUT%.gba}.ups"
