"""Compile the Tiled maps (maps/*.tmx) for the build.

  maps/<name>.tmx  ->  gen/maps/bs_<name>.dmp   (FE8 map data, LZ77-compressed; chapters #incbin it)
                   ->  gen/MapDefs.event        BS_MAP_TILESET_<NAME>: the 4 tileset bytes for the chapter data

So the .tmx is the single source of truth for both the tiles and which tileset a chapter loads.
"""
import glob, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fe8lib import encode_map, lz77_compress, lz77_decompress
import tmx

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
GEN = os.path.join(ROOT, "gen")
MIN_W, MIN_H = 15, 10          # one screen; smaller maps break the camera


def build(path):
    m = tmx.read(path)
    name, w, h = m["name"], m["width"], m["height"]
    if w < MIN_W or h < MIN_H:
        raise tmx.MapError("%s: %dx%d is smaller than one screen (%dx%d)" % (os.path.relpath(path), w, h, MIN_W, MIN_H))
    raw = encode_map(m["grid"])
    comp = lz77_compress(raw)
    back, _ = lz77_decompress(comp, 0)
    assert back == raw, "LZ77 round-trip failed for " + name
    out = os.path.join(GEN, "maps", "bs_" + name + ".dmp")
    old = open(out, "rb").read() if os.path.exists(out) else None
    if old != comp:
        open(out, "wb").write(comp)
    print("map %-10s %dx%d  raw %d -> lz %d bytes" % (name, w, h, len(raw), len(comp)))
    ts = m["tileset"]
    return '#define BS_MAP_TILESET_%s "BYTE 0x%02X 0x%02X 0x%02X 0x%02X"   // obj1 obj2 pal config' % (
        name.upper(), ts["obj1"], ts["obj2"], ts["pal"], ts["config"])


def main():
    os.makedirs(os.path.join(GEN, "maps"), exist_ok=True)
    paths = sorted(glob.glob(os.path.join(ROOT, "maps", "*.tmx")))
    if not paths:
        sys.exit("buildmaps: no maps in maps/")
    defs = ["// generated by tools/buildmaps.py from maps/*.tmx"] + [build(p) for p in paths]
    content = "\n".join(defs) + "\n"
    p = os.path.join(GEN, "MapDefs.event")
    if not os.path.exists(p) or open(p).read() != content:
        open(p, "w").write(content)


if __name__ == "__main__":
    try:
        main()
    except tmx.MapError as e:
        sys.exit("buildmaps: %s" % e)
