"""Port FE7 portraits into the FE8 build.

Reads the user's FE7U ROM, extracts portrait graphics for the characters listed in
data/fe7_faces.csv, and writes:
  gen/fe7faces/*.bin              raw blobs (never committed; derived from the user's ROM)
  gen/FE7Faces.event              repointed/expanded portrait table + new entries
  gen/FE7FaceDefs.event           #define BS_FACE_<NAME> <id>
  gen/face_codes.txt              [Load<Name>] text shortcuts, read by tools/gentext.py

FE7 and FE8 share the 28-byte portrait entry layout. FE8's Decompress accepts FE7's
LZ77-compressed main sheet as-is, so blobs are copied verbatim.
"""
import csv, os, struct, sys
sys.path.insert(0, os.path.dirname(__file__))
from fe8lib import lz77_decompress

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
FE7_FACE_TABLE = 0xC96584
FE8_FACE_TABLE = 0x8ACBC4
FE8_FACE_COUNT = 0xAC
FE8_FACE_PTR_REF = 0x5524          # literal pool in GetPortraitData
FIRST_NEW_ID = 0xAC
ENTRY = 28
MOUTH_SIZE = 0x600                 # 6 frames x 8 tiles x 32 bytes


def main(fe7_path, fe8_path):
    d7 = open(fe7_path, "rb").read()
    d8 = open(fe8_path, "rb").read()
    rows = [r for r in csv.DictReader(open(os.path.join(ROOT, "data", "fe7_faces.csv"))) if r["name"].strip()]
    outdir = os.path.join(ROOT, "gen", "fe7faces")
    os.makedirs(outdir, exist_ok=True)
    open(os.path.join(ROOT, "gen", "vanilla_faces.bin"), "wb").write(
        d8[FE8_FACE_TABLE: FE8_FACE_TABLE + FE8_FACE_COUNT * ENTRY])

    ev = ["// generated by tools/import_fe7_faces.py — do not edit",
          "PUSH", "ORG 0x%X" % FE8_FACE_PTR_REF, "POIN BS_PortraitTable", "POP", "",
          "ALIGN 4", "BS_PortraitTable:", "#incbin \"vanilla_faces.bin\""]
    defs = ["// generated by tools/import_fe7_faces.py — do not edit"]
    parse = []
    blobs = []
    for i, r in enumerate(rows):
        name = r["name"].strip()
        fid7 = int(r["fe7face"], 16)
        fid8 = FIRST_NEW_ID + i
        e = d7[FE7_FACE_TABLE + fid7 * ENTRY: FE7_FACE_TABLE + (fid7 + 1) * ENTRY]
        main, chibi, pal, mouth, card = struct.unpack_from("<5I", e, 0)
        tail = e[20:28]
        parts = {}
        for key, ptr in (("main", main), ("chibi", chibi)):
            o = ptr - 0x08000000
            _, used = lz77_decompress(d7, o)
            used = (used + 3) & ~3
            parts[key] = d7[o:o + used]
        parts["pal"] = d7[pal - 0x08000000: pal - 0x08000000 + 32]
        parts["mouth"] = d7[mouth - 0x08000000: mouth - 0x08000000 + MOUTH_SIZE] if mouth else None
        labels = {}
        for key, data in parts.items():
            if data is None:
                labels[key] = "0"
                continue
            fn = "%s_%s.bin" % (name.lower(), key)
            open(os.path.join(outdir, fn), "wb").write(data)
            lab = "BS_Face_%s_%s" % (name, key)
            labels[key] = lab
            blobs.append((lab, "fe7faces/" + fn))
        ev.append("POIN %s %s %s %s 0  // 0x%02X %s (FE7 face 0x%02X)" % (
            labels["main"], labels["chibi"], labels["pal"], labels["mouth"], fid8, name, fid7))
        ev.append("BYTE " + " ".join("0x%02X" % b for b in tail))
        defs.append("#define BS_FACE_%s 0x%02X" % (name.upper(), fid8))
        parse.append("[Load%s] = [LoadFace][0x%02X][0x1]" % (name, fid8))
    ev.append("")
    for lab, path in blobs:
        ev += ["ALIGN 4", "%s:" % lab, "#incbin \"%s\"" % path]
    open(os.path.join(ROOT, "gen", "FE7Faces.event"), "w").write("\n".join(ev) + "\n")
    open(os.path.join(ROOT, "gen", "FE7FaceDefs.event"), "w").write("\n".join(defs) + "\n")

    open(os.path.join(ROOT, "gen", "face_codes.txt"), "w").write("\n".join(parse) + "\n")
    print("imported %d FE7 portraits (ids 0x%02X-0x%02X)" % (len(rows), FIRST_NEW_ID, FIRST_NEW_ID + len(rows) - 1))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
