"""Generate the Tiled tilesets (maps/tilesets/*.tsx + .png) from your FE8 ROM.

The tileset images are Nintendo's graphics, so they are generated locally and never committed.
Each tileset has all 1024 metatiles of one FE8 tileset (32 per row); every tile carries a
"terrain" property (Plains, Forest, Fort...) that Tiled shows when you select it.

Usage:
  python3 tools/maptiles.py [FE8.gba]            tilesets for every map in maps/ (build.sh runs this)
  python3 tools/maptiles.py [FE8.gba] --vanilla  also every tileset a vanilla FE8 chapter uses
  python3 tools/maptiles.py [FE8.gba] --force    regenerate even if present
"""
import glob, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fe8lib import Rom, Tileset, Chapter, TERRAIN
import tmx

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
MAPS = os.path.join(ROOT, "maps")
OUT = os.path.join(MAPS, "tilesets")
VANILLA_CHAPTERS = 0x4F


def vanilla_users(rom):
    users = {}
    for c in range(VANILLA_CHAPTERS):
        ch = Chapter(rom, c)
        key = (ch.obj1, ch.obj2, ch.pal, ch.config)
        users.setdefault(key, []).append(c)
    return users


def generate(rom, ts, users, force=False):
    name = tmx.tileset_name(ts)
    tsx, png = os.path.join(OUT, name + ".tsx"), os.path.join(OUT, name + ".png")
    if not force and os.path.exists(tsx) and os.path.exists(png):
        return False
    tileset = Tileset(rom, ts["obj1"], ts["obj2"], ts["pal"], ts["config"])
    os.makedirs(OUT, exist_ok=True)
    tileset.sheet().save(png)
    key = tuple(ts[k] for k in tmx.TILESET_KEYS)
    used = users.get(key)
    label = "FE8 tileset obj %02X/%02X pal %02X config %02X" % key
    if used:
        label += " (vanilla chapters %s)" % ", ".join("0x%02X" % c for c in used)
    tiles = []
    for m in range(0x400):
        t = tileset.terrain[m]
        tname = TERRAIN[t] if t < len(TERRAIN) else "0x%02X" % t
        tiles.append('  <tile id="%d" type="%s"><properties><property name="terrain" value="%s"/>'
                     '<property name="metatile" value="0x%03X"/></properties></tile>' % (m, tname, tname, m))
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- generated by tools/maptiles.py from your FE8 ROM; do not edit or commit -->\n'
           '<tileset version="1.8" tiledversion="1.8.2" name="%s" tilewidth="16" tileheight="16" '
           'tilecount="1024" columns="32">\n'
           ' <image source="%s.png" width="512" height="512"/>\n%s\n</tileset>\n') % (label, name, "\n".join(tiles))
    open(tsx, "w", encoding="utf-8", newline="\n").write(xml)
    return True


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    rom = Rom(args[0] if args else os.path.join(ROOT, "roms", "fe8u.gba"))
    force = "--force" in sys.argv
    users = vanilla_users(rom)
    wanted = {}
    for path in sorted(glob.glob(os.path.join(MAPS, "*.tmx"))):
        m = tmx.read(path)
        wanted[tmx.tileset_name(m["tileset"])] = m["tileset"]
        if tmx.fix_tileset_source(path, m["tileset"]):
            print("maptiles: %s now uses tilesets/%s.tsx (to match its obj1/obj2/pal/config properties)"
                  % (os.path.basename(path), tmx.tileset_name(m["tileset"])))
    if "--vanilla" in sys.argv:
        for key in users:
            if key[0] == 0 or key[3] == 0:
                continue                      # unused chapter slots
            ts = dict(zip(tmx.TILESET_KEYS, key))
            wanted[tmx.tileset_name(ts)] = ts
    made = sum(generate(rom, ts, users, force) for ts in wanted.values())
    print("maptiles: %d tileset(s) ready in maps/tilesets/ (%d generated)" % (len(wanted), made))


if __name__ == "__main__":
    try:
        main()
    except tmx.MapError as e:
        sys.exit("maptiles: %s" % e)
