"""Port FE7 battle animations + FE7 character palettes into the FE8 build.

Every FE7 veteran fights with their own FE7 animation and personal palette (Kent's red
Paladin, Hector's Great Lord, Rath's Nomad Trooper...). FE7 and FE8 share the banim
format; a port = copy the sheets, relocate the absolute sheet pointers inside the
(decompressed) frame script, recompress it, and copy modes/OAM/palette.

Layout: all ported data goes into one blob at a fixed ROM address (BANIM_BASE), because
compressed scripts must contain absolute pointers that EA cannot patch.

Outputs:
  gen/banims.bin          sheets, scripts, OAM, palettes (derived from the user's FE7 ROM)
  gen/Banims.event        banim table entries, palette table entries, per-unit anim lists,
                          FE8 unique-palette rows, class anim lists for the new classes
Usage: python3 tools/port_banims.py FE8.gba FE7.gba
"""
import csv, os, struct, sys

sys.path.insert(0, os.path.dirname(__file__))
from fe8lib import lz77_decompress, lz77_compress
from fe7text import TextDecoder

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
GEN = os.path.join(ROOT, "gen")

BANIM_BASE = 0x01400000            # ROM offset reserved for ported banim data (8 MiB)
BANIM_LIMIT = 0x01C00000
FE7_BANIMS, FE8_BANIMS = 0xE00008, 0xC00008
FE8_FIRST_FREE_BANIM, FE8_BANIM_SLOTS = 0xCA, 0x1FF         # table is repointed and extended
FE8_BANIM_REFS = [0x59BD8, 0x5A600, 0x5A694, 0x5A82C, 0x6F6A8, 0x70940, 0x70A60]  # literal pools -> banim_data
FE7_CHARPAL, FE8_CHARPAL = 0xFD8008, 0xEF8008
FE8_CHARPAL_FIRST_FREE, FE8_CHARPAL_MAX = 108, 108 + 147
FE8_PALCFG, FE8_PALIT = 0x95E0A4, 0x95EEA4                    # [pid-1][7] class ids / palette idx+1
FE7_CHARS, FE7_CLASSES, FE8_CLASSES = 0xBDCE18, 0xBE015C, 0x807110
FE8_ITEMS, FE7_ITEMS = 0x809B10, 0xBE222C

# New FE8 classes that *are* FE7 classes: their class animation list is replaced outright.
CLASS_ANIM = {0x77: 0x07, 0x78: 0x09, 0x79: 0x08}            # Knight Lord, Great Lord (Hector), Blade Lord


def u32(d, o): return struct.unpack_from("<I", d, o)[0]
def u16(d, o): return struct.unpack_from("<H", d, o)[0]


class Blob:
    def __init__(self):
        self.data = bytearray()
        self.index = {}

    def add(self, key, data):
        if key in self.index:
            return self.index[key]
        while len(self.data) % 4:
            self.data.append(0)
        addr = 0x08000000 + BANIM_BASE + len(self.data)
        self.data += data
        self.index[key] = addr
        return addr


def lz_raw(d, off):
    """Return the exact compressed bytes of an LZ77 blob at off."""
    _, used = lz77_decompress(d, off)
    return bytes(d[off:off + used])


def norm(name):
    return "".join(ch for ch in name.lower() if ch.isalnum())


def anim_list(d, ptr):
    out, o = [], ptr - 0x08000000
    while True:
        w, i = u16(d, o), u16(d, o + 2)
        if w == 0:
            return out
        out.append((w, i))
        o += 4


def main(fe8_path, fe7_path):
    d8, d7 = open(fe8_path, "rb").read(), open(fe7_path, "rb").read()
    t7 = TextDecoder(d7, 0x6B8, 0x6BC, 0xB808AC)
    t8 = TextDecoder(d8, 0x6DC, 0x6E0, 0x15D48C)
    # item-name map FE7 -> FE8 (for item-specific animation entries such as javelins, hand axes)
    names8 = {}
    for i in range(1, 0xD0):
        n = norm(t8.decode(u16(d8, FE8_ITEMS + i * 36)))
        names8.setdefault(n, i)

    def item7_to_8(i7):
        return names8.get(norm(t7.decode(u16(d7, FE7_ITEMS + i7 * 36))))

    blob = Blob()
    banim_map = {}                     # FE7 banim id -> FE8 banim id
    next_id = [FE8_FIRST_FREE_BANIM]
    ev = ["// generated by tools/port_banims.py — do not edit", "PUSH"]
    table = []
    open(os.path.join(GEN, "vanilla_banims.bin"), "wb").write(d8[FE8_BANIMS:FE8_BANIMS + (FE8_FIRST_FREE_BANIM - 1) * 32])
    post = []                          # the literal pools sit in engine-protected functions:
    for ref in FE8_BANIM_REFS:         # tools/postpatch.py repoints them after linking
        assert u32(d8, ref) == 0x08000000 + FE8_BANIMS
        post.append("0x%X BS_BanimTable" % ref)
    open(os.path.join(GEN, "postpatch.txt"), "w").write("\n".join(post) + "\n")

    def port_banim(i7):
        if i7 in banim_map:
            return banim_map[i7]
        nid = next_id[0]
        assert nid <= FE8_BANIM_SLOTS, "out of free FE8 banim slots"
        next_id[0] += 1
        o = FE7_BANIMS + (i7 - 1) * 32
        name = d7[o:o + 12]
        modes, script, oamr, oaml, pal = struct.unpack_from("<5I", d7, o + 12)
        sc, _ = lz77_decompress(d7, script - 0x08000000)
        sc = bytearray(sc)
        # relocate frame sheet pointers: frame = [0x86xxxxxx, sheet ptr, oam offset]
        k = 0
        while k + 12 <= len(sc):
            w = u32(sc, k)
            if (w >> 24) == 0x86:
                sp = u32(sc, k + 4)
                new = blob.add(("sheet", sp), lz_raw(d7, sp - 0x08000000))
                struct.pack_into("<I", sc, k + 4, new)
                k += 12
            else:
                k += 4
        a_modes = blob.add(("modes", i7), bytes(d7[modes - 0x08000000: modes - 0x08000000 + 0x60]))
        a_script = blob.add(("script", i7), lz77_compress(bytes(sc)))
        a_oamr = blob.add(("oam", oamr), lz_raw(d7, oamr - 0x08000000))
        a_oaml = blob.add(("oam", oaml), lz_raw(d7, oaml - 0x08000000))
        a_pal = blob.add(("pal", pal), lz_raw(d7, pal - 0x08000000))
        table.append("// banim 0x%02X <- FE7 0x%02X %s" % (nid, i7, name.split(b"\0")[0].decode()))
        table.append("BYTE " + " ".join("0x%02X" % b for b in name))
        table.append("WORD 0x%08X 0x%08X 0x%08X 0x%08X 0x%08X" % (a_modes, a_script, a_oamr, a_oaml, a_pal))
        banim_map[i7] = nid
        return nid

    def port_list(fe7_class):
        """FE7 class animation list -> FE8 list text (weapon-type entries + name-mapped item entries)."""
        ptr = u32(d7, FE7_CLASSES + fe7_class * 84 + 0x34)
        out = []
        for w, i7 in anim_list(d7, ptr):
            if w < 0x100:
                i8 = item7_to_8(w)
                if i8 is None:
                    continue
                w = i8
            out.append((w, port_banim(i7)))
        return out

    lists = []                         # (label, entries)

    def emit_list(label, entries):
        lists.append((label, entries))
        return label

    # --- new classes: whole class animation list is FE7's ---
    for cid, c7 in CLASS_ANIM.items():
        lab = emit_list("BS_BanimList_Class%02X" % cid, port_list(c7))
        ev.append("ORG 0x%X  // class 0x%02X battle anims" % (FE8_CLASSES + cid * 84 + 0x34, cid))
        ev.append("POIN %s" % lab)

    # --- every FE7 character: their FE7 class anims + FE7 personal palette ---
    rows = list(csv.DictReader(open(os.path.join(ROOT, "data", "cast.csv"))))
    custom = []
    palcfg = {}                        # pid -> [(class, palidx+1)]
    next_pal = [FE8_CHARPAL_FIRST_FREE]
    pal_map = {}
    for r in rows:
        pid, target = int(r["pid"], 16), int(r["class"], 16)
        if r["game"] == "fe8":
            src = int(r["src"], 16)
            if src != pid:             # moved FE8 character: carry their unique palettes over
                cfg = d8[FE8_PALCFG + (src - 1) * 7: FE8_PALCFG + src * 7]
                it = d8[FE8_PALIT + (src - 1) * 7: FE8_PALIT + src * 7]
                palcfg[pid] = [(cfg[k], it[k]) for k in range(7) if cfg[k]]
            continue
        src = int(r["src"], 16)
        o = FE7_CHARS + src * 52
        c0 = d7[o + 5]
        c7 = c0
        promo7 = u32(d7, FE7_CLASSES + c0 * 84 + 0x28) & 0x100
        if not promo7 and target not in (0x26, 0x25, 0x4D, 0x46):       # growing/dancer/bard keep base class
            c7 = d7[FE7_CLASSES + c0 * 84 + 5] or c0
        pal_idx = (d7[o + 0x24] or d7[o + 0x23]) if (c7 != c0 or promo7) else d7[o + 0x23]
        if target in CLASS_ANIM:
            ents = None                # class list already is FE7's
        else:
            ents = port_list(c7)
            if ents:
                custom.append((pid, target, emit_list("BS_BanimList_%s" % r["key"], ents)))
        if pal_idx:
            if pal_idx not in pal_map:
                n = next_pal[0]
                assert n < FE8_CHARPAL_MAX, "out of character palette slots"
                next_pal[0] += 1
                po = FE7_CHARPAL + (pal_idx - 1) * 16
                a = blob.add(("cpal", pal_idx), lz_raw(d7, u32(d7, po + 12) - 0x08000000))
                ev.append("ORG 0x%X  // character palette %d <- FE7 %s" % (FE8_CHARPAL + n * 16, n, d7[po:po + 12].split(b"\0")[0].decode()))
                ev.append("BYTE " + " ".join("0x%02X" % b for b in d7[po:po + 12]))
                ev.append("WORD 0x%08X" % a)
                pal_map[pal_idx] = n
            palcfg[pid] = [(target, pal_map[pal_idx] + 1)]

    # unique-palette rows (pid-1): rewrite every cast row so nobody inherits a vanilla neighbour's palette
    for r in rows:
        pid = int(r["pid"], 16)
        if r["game"] == "fe8" and int(r["src"], 16) == pid:
            continue                   # FE8 characters in their own slot keep vanilla rows
        ents = palcfg.get(pid, [])[:7]
        cfg = [c for c, _ in ents] + [0] * (7 - len(ents))
        it = [p for _, p in ents] + [0] * (7 - len(ents))
        ev.append("ORG 0x%X  // palette row for pid 0x%02X %s" % (FE8_PALCFG + (pid - 1) * 7, pid, r["key"]))
        ev.append("BYTE " + " ".join(str(x) for x in cfg))
        ev.append("ORG 0x%X" % (FE8_PALIT + (pid - 1) * 7))
        ev.append("BYTE " + " ".join(str(x) for x in it))

    # banim data blob at its fixed address
    ev.append("ORG 0x%X" % BANIM_BASE)
    ev.append('#incbin "banims.bin"')
    ev.append("ASSERT 0x%X - CURRENTOFFSET" % BANIM_LIMIT)
    # per-unit custom animation table (Individual Animation patch in C-SkillSys)
    ev.append("ORG gpCustomAnimeTable1")
    ev.append("POIN BS_CustomAnimeTable")
    ev.append("ORG gpCustomAnimeTable2")
    ev.append("POIN BS_CustomAnimeTable")
    ev.append("POP")
    ev += ["", "ALIGN 4", "BS_BanimTable:", '#incbin "vanilla_banims.bin"'] + table + ["WORD 0 0 0 0 0 0 0 0"]
    ev += ["", "ALIGN 4", "BS_CustomAnimeTable:"]
    for pid, target, lab in custom:
        ev.append("BYTE 0x%02X 0x%02X 0 0; POIN %s" % (pid, target, lab))
    ev.append("WORD 0 0")
    for lab, ents in lists:
        ev += ["ALIGN 4", "%s:" % lab] + ["SHORT 0x%04X 0x%04X" % e for e in ents] + ["WORD 0"]
    assert BANIM_BASE + len(blob.data) <= BANIM_LIMIT
    open(os.path.join(GEN, "banims.bin"), "wb").write(bytes(blob.data))
    open(os.path.join(GEN, "Banims.event"), "w").write("\n".join(ev) + "\n")
    print("banims: %d FE7 animations (ids 0x%02X-0x%02X), %d personal palettes, %d unit lists, %.1f MiB" % (
        len(banim_map), FE8_FIRST_FREE_BANIM, next_id[0] - 1, len(pal_map), len(custom), len(blob.data) / 1048576))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
